### ISSUE TITLE
Anonymisation service 

### ISSUE THREAD

**Issue by sunfish-prj** [sunfish-prj/Anonymisation-Interface#2]
Add default anonymisation service and use configuration parameters to invoke it from the app

**Comment by sunfish-prj** [comment]
no documentation on setting-up dummy service available

https://github.com/sunfish-prj/Anonymisation-Interface/tree/master/anonym-service

**Comment by rsindper** [comment]
Do we still need this dummy service? Which anonymisation service do you want to use exactly now? @andreamargheri

**Comment by sunfish-prj** [comment]
No additional implementation is needed, but what done so far should be usable and this means a user must be able to install/invoke the dummy service. Agreed? 

Just add a few line on how to install the code, that is enough

**Comment by rsindper** [comment]
yes. agreed and fixed
